version: "3.3"
services:
  audiotopic-api:
    image: audiotopic-api:latest
    container_name: audiotopic-api
    environment:
      OPEN_AI_TOKEN: sk-change-me
      TENSORFLOW_MODEL_NAME: "t5-small"
    
    command: sh -c "pipenv run uvicorn src.api:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  audiotopic-app:
    image: audiotopic-app:latest
    container_name: audiotopic-app
    environment:
      HOST: 0.0.0.0
      PORT: 3000   
    depends_on:
      - audiotopic-api
    command: sh -c "./wait-for-api.sh && pnpm run dev"
    ports:
      - "3000:3000"
