version: "3.3"
services:
  audiotopic-api:
    image: audiotopic-api:latest
    container_name: audiotopic-api

    command: sh -c "pipenv run uvicorn src.api:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
#     networks:
#       - audiotopic-net

# networks:
#   audiotopic-net:
